const page=await figma.getNodeByIdAsync('2:2');await figma.setCurrentPageAsync(page);
const title=text(page,'SmartLight / Android',40,'text','Medium');title.x=120;title.y=48;
const out={};
const home=phone(page,'My room',120);out['My room']=home.frame;home.content.itemSpacing=16;
const hrow=row(home.content,'Room header',372,12);const h=stack(hrow,'Room title',248,2);grow(h);text(h,'YOUR SPACE',11,'muted','Medium');text(h,'My room.',32,'text','Semi Bold');const dots=row(hrow,'Room menu',44,0,11,'surface',99);icon(dots,'more','muted',22);
dotBadge(home.content,'3 lights connected');roomHero(home.content,372,true);
sectionTitle(home.content,'Your lights','3 devices',372);const one=light(home.content,'White','Wipro Tube 1','Warm white · 3200 K',372);navTo(one,'Light');light(home.content,'White','Wipro Tube 2','Warm white · 3200 K',372);light(home.content,'Colour','Tapo Strip','Soft lavender · Colour',372);
const moods=sectionTitle(home.content,'Set the mood','All scenes',372);navTo(moods,'Scenes');const moodRow=row(home.content,'Quick scenes',372,12);for(const s of ['Golden hour','Movie']){const node=scene(moodRow,s,180);navTo(node,'Scene active');}
const gallery=phone(page,'Scenes',612,'Scenes');out.Scenes=gallery.frame;
const gh=row(gallery.content,'Scene header',372,12);grow(text(gh,'Scenes',32,'text','Semi Bold'));const add=row(gh,'New scene',48,0,13,'mint',16);icon(add,'plus','ink',22);navTo(add,'Editor');
text(gallery.content,'One tap. A different feeling.',14,'muted');const filters=row(gallery.content,'Scene filters',372,8);chip(filters,'All scenes',true);chip(filters,'My scenes');chip(filters,'Presets');
text(gallery.content,'MADE BY YOU',11,'muted','Medium');const custom=row(gallery.content,'Custom scenes',372,12);navTo(scene(custom,'Golden hour',180),'Scene active');navTo(scene(custom,'Reading',180),'Editor');
sectionTitle(gallery.content,'Everyday favourites',null,372);
for(const pair of [['Study','Movie'],['Chill','Sleep']]){const r=row(gallery.content,'Preset scenes',372,12);for(const s of pair)navTo(scene(r,s,180),'Scene active');}
const create=action(gallery.content,'Create a scene',false,372);navTo(create,'Editor');
const editor=phone(page,'New scene',1104,'Scenes',false);out.Editor=editor.frame;
const er=row(editor.content,'Editor header',372,12);const back=row(er,'Back to scenes',44,0,11,null);icon(back,'back','text',22);navTo(back,'Scenes');text(er,'New scene',24,'text','Semi Bold');editorContents(editor.content,372);
const detail=phone(page,'Light control',1596,'My room');out.Light=detail.frame;
const dh=row(detail.content,'Light header',372,12);const db=row(dh,'Back',44,0,11,null);icon(db,'back','text',22);navTo(db,'My room');grow(text(dh,'Wipro Tube 1',24,'text','Semi Bold'));icon(dh,'more','muted',22);dotBadge(detail.content,'Connected');
const visual=stack(detail.content,'Light preview',372,16,24,'surface',24);visual.counterAxisAlignItems='CENTER';const beam=box(visual,'Warm white light',324,92,null);const glow=rect(beam,'Soft light',276,48,'warm',24);glow.x=24;glow.y=22;glow.opacity=.08;const bulb=rect(beam,'Batten',250,12,'warm',6);bulb.x=37;bulb.y=40;const toggle=row(visual,'Power',324,12);grow(text(toggle,'Light is on',16,'text','Medium'));inst(toggle,comps.toggleOn);
const bright=stack(detail.content,'Brightness',372,12,20,'surface',20);labelPair(bright,'Brightness','72%',332,16);slider(bright,332,72,'warm');
const temp=stack(detail.content,'White temperature',372,20,20,'surface',20);labelPair(temp,'White temperature','3200 K',332,16);const tempbar=box(temp,'Temperature',332,32,null);const ramp=rect(tempbar,'Temperature ramp',332,8,'warm',4);ramp.y=12;ramp.fills=gradient('#EDBD79','#ADCFF1');const tk=circle(tempbar,24,'text');tk.x=88;tk.y=4;labelPair(temp,'Warm','Cool',332,12);const whites=row(temp,'White presets',332,8);chip(whites,'Warm',true);chip(whites,'Neutral');chip(whites,'Cool');
const saveAs=action(detail.content,'Save as a scene',false,372);navTo(saveAs,'Editor');
const settings=phone(page,'Settings',2088,'Settings');out.Settings=settings.frame;
heading(settings.content,'Settings','Make SmartLight feel like yours.',372);
text(settings.content,'YOUR SETUP',11,'muted','Medium');settingRow(settings.content,'bulb','Connected lights','2 Wipro tubes · 1 Tapo strip',372);settingRow(settings.content,'transfer','Transfer setup','Move light connections to another device',372);text(settings.content,'PREFERENCES',11,'muted','Medium');settingRow(settings.content,'moon','Appearance','Dark',372);settingRow(settings.content,'wifi','Connection diagnostics','Check a light that isn’t responding',372);
const local=stack(settings.content,'Local control note',372,10,20,'surface',20);icon(local,'shield','mint',24);text(local,'Your room, your control.',20,'text','Semi Bold');text(local,'Control your lights while you’re on the same Wi-Fi. Your connections are stored securely on this device.',14,'muted','Regular',332);text(local,'Custom scenes are saved on this device.',12,'muted','Regular',332);
text(settings.content,'SmartLight · Designed for everyday light',12,'muted');
const saved=phone(page,'Scene saved',2580,'Scenes');out['Saved scene']=saved.frame;
const toast=row(saved.content,'Success',372,12,16,'raised',16);icon(toast,'check','mint',24);text(toast,'Golden hour saved',16,'mint','Medium');heading(saved.content,'Your new favourite.','Ready whenever the room needs a softer glow.',372);scene(saved.content,'Golden hour',180);text(saved.content,'Wipro Tube 1 · 35% · Warm white\nWipro Tube 2 · 35% · Warm white\nTapo Strip · 20% · Soft peach',14,'muted','Regular',372);const apply=action(saved.content,'Apply scene',true,372);navTo(apply,'Scene active');const edit=action(saved.content,'Edit scene',false,372);navTo(edit,'Editor');const done=action(saved.content,'Back to scenes',false,372);navTo(done,'Scenes');
const active=phone(page,'Scene active',3072,'My room');out['Scene active']=active.frame;heading(active.content,'Golden hour.','A softer glow, all around.',372);const applyToast=row(active.content,'Scene applied',372,10,16,'raised',16);icon(applyToast,'check','mint',22);text(applyToast,'Applied to 3 lights',14,'mint','Medium');roomArt(active.content,372,220);light(active.content,'White','Wipro Tube 1','35% · Warm white',372,true);light(active.content,'White','Wipro Tube 2','35% · Warm white',372,true);light(active.content,'Colour','Tapo Strip','20% · Soft peach',372,true);
for(const link of links){const n=await figma.getNodeByIdAsync(link.id);let root=n;while(root.parent && root.parent.type!=='PAGE')root=root.parent;if(root.id===out[link.target].id)continue;await n.setReactionsAsync([{trigger:{type:'ON_CLICK'},actions:[{type:'NODE',destinationId:out[link.target].id,navigation:'NAVIGATE',transition:{type:'DISSOLVE',duration:.18,easing:{type:'EASE_OUT'}}}]}]);}
page.flowStartingPoints=[{nodeId:home.frame.id,name:'Android · SmartLight'}];figma.viewport.scrollAndZoomIntoView([home.frame,gallery.frame]);
return {createdNodeIds:[...new Set([...affected,...Object.values(out).flatMap(allIds)])],mutatedNodeIds:[page.id],screens:Object.fromEntries(Object.entries(out).map(([k,v])=>[k,evidence(v)])),linkCount:links.length};
